### ISSUE TITLE
dumb-init: cannot execute binary file: Exec format error on Raspberry Pi

### ISSUE THREAD

**Issue by AusMatt** [networkboot/docker-dhcpd#10]
I see that the Dockerfile simply copies an amd64 build of dumb-init to /usr/bin/dumb-init
This of course fails when using networkboot/dhcpd on other architectures such as armhf.
Running the container on such platforms results in output:
```
/entrypoint.sh: line 66: /usr/bin/dumb-init: cannot execute binary file: Exec format error
/entrypoint.sh: line 66: /usr/bin/dumb-init: Success
```

This is discussed here: [Yelp/dumb-init issue 138](https://github.com/Yelp/dumb-init/issues/138).
I've used the workaround of:
```
wget http://ftp.us.debian.org/debian/pool/main/d/dumb-init/dumb-init_1.2.0-1_armhf.deb
ar -x *.deb
tar -xvf data.tar.xz
cp usr/bin/dumb-init util/dumb-init_1.2.0_armhf
```
... and then editing the Dockerfile to use this binary.
A nice solution won't be easy.

**Comment by robinsmidsrod** [comment]
Well, this image is made for the x86_64 architecture, so I don't really see this as a fault of the current Dockerfile. I believe the Docker hub supports some form of specifying architecture, but it's quite possible this image does not specify it. If you can point me at the correct way to create a multi-arch Dockerfile and how to use the armhf Ubuntu base and armhf dumb-init deb I can try to make it work. Pull requests are most welcome, as I don't have any hardware to test it on.

**Comment by AusMatt** [comment]
@robinsmidsrod , I'm not that experienced with Docker so haven't learnt how to do this, I've just copied the armhf dumb-init into util and edited your Dockerfile as needed (including basing it off ubuntu:latest) and then run your build script on the armhf platform. I'm happy just to contribute a piece of the puzzle at this time and to report that it can be made to work. I'm now happily using my LibreELEC Raspberry Pi as the local DHCP server. I hope that someone else can complete the puzzle for you.

**Comment by robinsmidsrod** [comment]
I'm wondering if we should stop using dumb-init and use the docker run --init parameter instead. Then we wouldn't have an issue with this at all.

**Comment by AusMatt** [comment]
I would certainly prefer not requiring a binary as part of a Docker image build. My work is much easier if I can show that everything is either built from source or a script. Another solution that would suit me would be to build dumb-init from it's source.
