### ISSUE TITLE
run script doesn't support ARM

### ISSUE THREAD

**Issue by terrillmoore** [networkboot/docker-dhcpd#12]
Change #11 added support for building an arm image; however, the `run` script wasn't changed.

**Comment by robinsmidsrod** [comment]
@terrillmoore The `run` script is just a convenience script I added to make it easier to iterate on a configuration while testing out. It's not expected to be used in any production situation. But regardless, I've given some feedback on PR #13. If you're running this image in production, I would expect you to make your own systemd unit, service startup script or use Docker directly to run it in daemon mode.

**Comment by robinsmidsrod** [comment]
With the upgrade to Ubuntu 18.04 and the use of the bundled dumb-init there should be no need for a custom ARM-specific run script either.
