### ISSUE TITLE
Don't do apt-get dist-upgrade in Dockerfile

### ISSUE THREAD

**Issue by ooxi** [networkboot/docker-dhcpd#15]
According to [Docker best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get), you should not do `upgrade` or `dist-upgrade` in your Dockerfile.

**Comment by robinsmidsrod** [comment]
Removed apt-get dist-upgrade in commit 8337f5b30320c63110b2daf542b85e49c2391a4e .
