### ISSUE TITLE
Doing man dhcpd.conf inside the container returns error

### ISSUE THREAD

**Issue by robinsmidsrod** [networkboot/docker-dhcpd#18]
It seems like the upgrade to Ubuntu 18.04 broke the man page lookup feature that is mentioned in the README. Most likely it is an APT configuration setting that needs to be tweaked, because the actual man files in /usr/share/man are not present. They were present when we used Ubuntu 14.04. I can't recall if they worked with 16.04, but it should be fixed.

If anyone knows how to enable installation of man pages for APT then please provide some feedback.

**Comment by midlan** [comment]
+1
I've run in same issue.

**Comment by robinsmidsrod** [comment]
I've merged in the patch from @jakschu that should fix this issue. New image should be built automatically. Cheers!
