### ISSUE TITLE
Could you add a versioned tag to Docker Hub?

### ISSUE THREAD

**Issue by accnops** [networkboot/docker-dhcpd#24]
Now there's only :latest, which adds risk to our production environment.

**Comment by robinsmidsrod** [comment]
@accnops Adding a version means adding a versioning scheme (e.g. semantic versioning, semver.org), which means that a backwards/forwards policy for API/usage stability should be created. Since this project is mostly a one-man-show I don't really have the resources to maintain multiple versions, which is why only the `:latest` tag is specified. I'm doing my best to not break the execution "contract" specified in the documentation. If I ever need to break it, I might introduce versioning at that point.

**Comment by accnops** [comment]
This means that all existing users of your image would possibly have problems when a breaking change and thus versioning is introduced. That's because the tag we use would still be :latest, unless we manage to catch a notification of sorts on github/docker and change it in time.

Having versioning doesn't mean you have to support all versions. It just means users can "pin" to a specific version. It's much safer. What do you think?

**Comment by robinsmidsrod** [comment]
@accnops Would you be willing to draft a document that can serve as the basis for API/usage stabilitypolicy, in accordance with the semver specification? In addition, could you help out with what must be done in the automatic build setup (I'm using Docker Hub autobuild environment)?

Preferably, to tag a new version I'd like to just do `git tag vx.y.z` on a specific commit, push that to GitHub and the build environment should take care of building the image with that tag automatically.

If you could spell it out in step-by-step actions that need to be done for this to work I'd be willing to implement it.

**Comment by waisbrot** [comment]
Assuming you want to use the tag v1.2.3, on Docker Hub do

1. Manage repository > Builds
2. Under Build Rules, you'll see an existing rule to build from the `master` branch
3. Click the `+` to add a new rule
4. `Tag` rule, source `/^v([0-9.]+)$/`, docker tag `{\1}`

I believe the result should look like this:
![image](https://user-images.githubusercontent.com/1170218/86786771-62667100-c032-11ea-8ae1-21f0f37e3872.png)


IMO that should be sufficient. You'd push tags corresponding to the version of dhcpd and users could pin to whatever version they liked.

**Comment by robinsmidsrod** [comment]
@waisbrot I've set up the above configuration in Docker Hub and pushed the v1.0.0 tag on the existing commit (https://github.com/networkboot/docker-dhcpd/tree/2ff24759518778e1cff6009cfede61257e4a5be8), but the build just hangs in "PENDING" state, and the UI says "Logs are not available yet" and "Dockerfile is not available yet", and this is 28 minutes after the build was created. Do you know what could be the reason for this happening?

**Comment by robinsmidsrod** [comment]
@waisbrot After trying to build for about 4 hours I had to cancel the build. Hopefully it'll build correctly when I push some more commits and tag another release.

**Comment by waisbrot** [comment]
AFAIK, "pending" just means it's waiting on docker.com's infrastructure. Maybe they were having problems or a slow day. If you pushed a tag and that moved it to "pending" then I think you're set up correctly.

**Comment by robinsmidsrod** [comment]
Unfortunately Docker Hub has removed automatic builds from the free tier, so this issue has become non-solvable using Docker Hubs infrastructure, without incurring recurring costs. This means I'll need to tag and build releases manually, or until another CI toolchain can do the job without additional monetary cost.
