### ISSUE TITLE
Fails to launch on new installation

### ISSUE THREAD

**Issue by chris-gross** [networkboot/docker-dhcpd#28]
Currently attempting to utilize this image to test for a production use. When I try to start it though, I get an error in the startup:

`Internet Systems Consortium DHCP Server 4.3.5
Copyright 2004-2016 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Config file: /data/dhcpd.conf
Database file: /var/lib/dhcp/dhcpd.leases
PID file: /var/run/dhcpd.pid
Can't open lease database /var/lib/dhcp/dhcpd.leases: No such file or directory --
  check for failed database rewrite attempt!
Please read the dhcpd.leases manual page if you
don't know what to do about this.

If you think you have received this message due to a bug rather
than a configuration issue please read the section on submitting
bugs on either our web page at www.isc.org or in the README file
before submitting a bug.  These pages explain the proper
process and the information we find helpful for debugging..

exiting.`

Seems it's not creating the lease file thus stops. Any hints or clues would be useful in this, thanks!

**Comment by robinsmidsrod** [comment]
@chris-gross The `/data` volume needs to be writable by the user running dhcpd. The container entrypoint tries ensure dhcpd is run as the same user that owns the folder, but your environment might not allow that. You probably have some setting or configuration that puts the dhcpd.leases file in /var/lib/dhcp (the default) instead of in /data.

**Comment by chris-gross** [comment]
Yep I'm dumb, I copied my production configuration file over without auditing too in depth and there it was, a hard set leases location someone set.
