### ISSUE TITLE
Bugreport: dhcpd process not running as dhcpd user

### ISSUE THREAD

**Issue by yscialom** [networkboot/docker-dhcpd#33]
Hello. Please help me make sense of the following.

Summary
===

Although the `dhcpd` process is supposed to run as the `dhcpd` user<sup>1</sup> --- so created files (e.g. `.leases`) are coherent with the file ownershiup of `/data` --- it appears `dhcpd` always runs as `root` and create files owned by `root`.

<sup>1</sup> [`networkboot/docker-dhcpd/blob/master/README.md §Notes`](https://github.com/networkboot/docker-dhcpd/blob/v1.2.0/README.md#notes)
> The entrypoint script in the docker image takes care of running the DHCP server as the same user that owns the data folder. This ensures that the permissions on the files inside the data folder is kept consistent. If the data folder is owned by root, dhcpd is run as the normal dhcpd user.

Description
===

Context
---
* **Product version**: 1.2.0
* **Pulled from**: https://hub.docker.com/r/networkboot/dhcpd
* **System**: Ubuntu Server LTS 20.04
* **Docker version**: 20.10.12

Test
---
1. In an empty directory `/tmp/issue-wrong-user`, create `data/dhcpd.conf`:
```
subnet 192.168.1.0 netmask 255.255.255.0 {
    option routers                  192.168.1.254;
    option subnet-mask              255.255.255.0;
    option domain-name-servers      1.1.1.1;
    range                           192.168.1.1 192.168.1.253;
}
```

2. Handle file ownership:
```shell
sudo chown --recursive 666:666 /tmp/issue-wrong-user/data #note: user and group #666 do not have to exist
```

3. Start dhcpd
```shell
cd /tmp/issue-wrong-user
docker run -d --rm --name dhcpd --init --net host -v "$(pwd)/data":/data networkboot/dhcpd:1.2.0
```

4. Check file created
```shell
find . -exec ls -l {} \;
```

5. Check user running `dhcpd`
```shell
docker exec dhcpd ps -ef
```

Observed Behaviour
---
* Some files are owned by `root` (step 4).
* `dhcpd` runs as `root` (step 5).
```
❯ find . -exec ls -l {} \;
total 4
drwxrwxr-x 2 666 666 4096 juil.  5 16:27 data
total 8
-rw-rw-r-- 1  666  666 256 juil.  5 16:26 dhcpd.conf
-rw-r--r-- 1 root root 277 juil.  5 16:27 dhcpd.leases
-rw-r--r-- 1  666  666   0 juil.  5 16:27 dhcpd.leases~
-rw-rw-r-- 1 666 666 256 juil.  5 16:26 ./data/dhcpd.conf
-rw-r--r-- 1 666 666 0 juil.  5 16:27 ./data/dhcpd.leases~
-rw-r--r-- 1 root root 277 juil.  5 16:27 ./data/dhcpd.leases

❯ docker exec dhcpd ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  0 14:27 ?        00:00:00 /sbin/docker-init -- /entrypoint.sh
root           7       1  0 14:27 ?        00:00:00 /usr/bin/dumb-init -- /usr/sbin/dhcpd -4 -f -d --no-pid -cf /data/dhcpd.conf -lf /data/dhcpd.leases
root          32       7  0 14:27 ?        00:00:00 /usr/sbin/dhcpd -4 -f -d --no-pid -cf /data/dhcpd.conf -lf /data/dhcpd.leases
root          36       0  0 14:28 ?        00:00:00 ps -ef
```

Expected Behaviour
---
* All files are owned by `666:666` (step 4).
* `dhcpd` runs as `dhcpd` (step 5).

Preliminary Analysis
---
`entrypoint.sh` does indeed make sure the `dhcpd` user has the same numeric ids as the owner of `/data`:
```shell
    data_dir="/data"
    # [...]
    uid=$(stat -c%u "$data_dir")
    gid=$(stat -c%g "$data_dir")
    if [ $gid -ne 0 ]; then
        groupmod -g $gid dhcpd
    fi
    if [ $uid -ne 0 ]; then
        usermod -u $uid dhcpd
    fi
```
taken from: [`util/entrypoint.sh:38`](https://github.com/networkboot/docker-dhcpd/blob/v1.2.0/util/entrypoint.sh#L38)

But as `dhcpd` runs as `root` (no `USER` in [`Dockerfile`](https://github.com/networkboot/docker-dhcpd/blob/v1.2.0/Dockerfile)) nor any `su` in `entrypoint.sh`, the fact that `dhcpd` has those correct ids is useless.

Note: One can check `dhcpd` is correctly set:
```shell
docker exec dhcpd grep ^dhcpd /etc/passwd
```

**Comment by robinsmidsrod** [comment]
To run as a non-root user it seems the `-user <uid>` and `-group <gid>` parameters to `dhcpd` needs to be used. Can you verify that it is indeed the case?

**Comment by yscialom** [comment]
It works @robinsmidsrod!

Diff
---
```
iff --git a/util/entrypoint.sh b/util/entrypoint.sh
index 63883fd..70266cd 100755
--- a/util/entrypoint.sh
+++ b/util/entrypoint.sh
@@ -69,7 +69,7 @@ if [ -n "$IFACE" ]; then
         echo "You must add the 'docker run' option '--net=host' if you want to provide DHCP service to the host network."
     fi
 
-    $run /usr/sbin/dhcpd -$DHCPD_PROTOCOL -f -d --no-pid -cf "$data_dir/dhcpd.conf" -lf "$data_dir/dhcpd.leases" $IFACE
+    $run /usr/sbin/dhcpd -$DHCPD_PROTOCOL -f -d --no-pid -cf "$data_dir/dhcpd.conf" -lf "$data_dir/dhcpd.leases" -user dhcpd -group dhcpd $IFACE
 else
     # Run another binary
     $run "$@"
```

Build
---
```
./build
```

Test
---
As per modus operandi.

Observed Behaviour
---
```
❯ find . -exec ls -l {} \;
total 4
drwxrwxr-x 2 666 666 4096 juil.  5 17:16 data
total 8
-rw-rw-r-- 1 666 666 256 juil.  5 16:26 dhcpd.conf
-rw-r--r-- 1 666 666 274 juil.  5 17:16 dhcpd.leases
-rw-r--r-- 1 666 666   0 juil.  5 17:16 dhcpd.leases~
-rw-rw-r-- 1 666 666 256 juil.  5 16:26 ./data/dhcpd.conf
-rw-r--r-- 1 666 666 0 juil.  5 17:16 ./data/dhcpd.leases~
-rw-r--r-- 1 666 666 274 juil.  5 17:16 ./data/dhcpd.leases

❯ docker exec dhcpd ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  0 15:16 ?        00:00:00 /sbin/docker-init -- /entrypoint.sh
root           7       1  0 15:16 ?        00:00:00 /usr/bin/dumb-init -- /usr/sbin/dhcpd -4 -f -d --no-pid -cf /data/dhcpd.conf -lf /data/dhcpd.leases -user dhcpd -group dhcpd
dhcpd         32       7  0 15:16 ?        00:00:00 /usr/sbin/dhcpd -4 -f -d --no-pid -cf /data/dhcpd.conf -lf /data/dhcpd.leases -user dhcpd -group dhcpd
root          36       0  0 15:16 ?        00:00:00 ps -ef

```

Can you integrate the correction?

**Comment by yscialom** [comment]
FYI: I've read multiple times the [man page of dhcpd](https://linux.die.net/man/8/dhcpd) to see if such options existed, but **no mention of `-user` or `-group`**!.

**Comment by robinsmidsrod** [comment]
@yscialom There is one more issue with this. If the data directory is owned by root then we should probably not run `dhcpd` with the `-user/-group` parameters, right? So we need to support both as root and as non-root.

**Comment by yscialom** [comment]
You're right, I overlooked the zero equality test for variables `$uid` and `$gid`. I'd suggest to remove them with it. I'll do the PR.

Rationale: you can have multiple super users on the same system.

If `/data` is own by root (user whose uid is zero), `$uid` will be zero and dhcp will become a super user. I'd be better to test it to validate the logic, but I foresee no reason why it shouldn't work.
