### ISSUE TITLE
Problems with DHCP server with finicky Ethernet devices

### ISSUE THREAD

**Issue by wickywaka** [networkboot/docker-dhcpd#37]
The dhcp server stops serving IP addresses when the Ethernet interface becomes unavailable for a second or so. I don't want to go into the kernel to fix the issue as its a problem from the vendor but I would like the DHCP server to know that the Ethernet interface is available and start serving IP addresses.

I know this description is a bit vague, but any help would be highly appreciated.

For more details, see here:
https://revolutionpi.de/forum/viewtopic.php?p=12904#p12904

**Comment by robinsmidsrod** [comment]
Technically this is an issue for the DHCP server process itself. If the network interface is not available when we want to start the process we can possibly work around it, but if the ethernet device goes offline while dhcpd is running, it's up to that process to "reconnect" to the device. I think the right approach is for dhcpd to use the kernel netlink interface to listen for up/down events and suspend service whenever the interface is unavailable and resume service when it comes back. You should go upstream to ISC dhcpd and report a bug/feature request to them to determine how to best solve the issue of intermittently connected devices.

To be honest, I wouldn't trust a device that doesn't keep its interfaces connected consistently with DHCP service for my network. Too flakey in my opinion. DHCP service needs to be rock solid in a network, or you have so many other issues to troubleshoot.

**Comment by robinsmidsrod** [comment]
Haven't seen any work on this, and no indication that an upstream bug was filed, so closing as stale.
