### ISSUE TITLE
Question: running as  a docker service?

### ISSUE THREAD

**Issue by demaniak** [networkboot/docker-dhcpd#9]
Am I correct in saying that there is still no way to run as a docker service due to security(?) limitations imposed when running as a service?

**Comment by robinsmidsrod** [comment]
@demaniak I'm not sure. What are the limitations imposed when running as a service?

**Comment by demaniak** [comment]
Hm. Well, as I understand it, to implement DHCP, some low level network access is required. That access is apparently (last I check) not available to docker containers running as services.

I believe [this link is relevant](https://forums.docker.com/t/docker-service-with-cap-add-net-admin-device/18245). Specifically the ‐cap‐add=NET_ADMIN.

I would love to run DHCP en DNS as docker swarm services, to gain the automatic recovery-in-case-of-host-failure power.
DNS, btw, works fine (I'm running PiHole as a swarm service on my home net, and that uses DNSmasq to support it's magic).

But thanks for the reply - I'm just hoping against hope that somebody's found some magic loop hole :)

**Comment by robinsmidsrod** [comment]
Well, when I run it on my home network I run it as an upstart service with --network=host and that's it. I don't assign it any more capabilities than that.

```
# cat /etc/init/dhcpd-green.conf
description "ISC DHCP server for green network (VLAN 1)"

start on runlevel [2345]
stop on runlevel [!2345]

respawn
respawn limit 10 5

exec docker run --rm --name dhcpd-green --network host -v /etc/dhcp/green:/data networkboot/dhcpd eth0
```

**Comment by demaniak** [comment]
@robinsmidsrod I will have to try it, but [looking at this](https://docs.docker.com/network/host/), I suspect you MIGHT just have pointed me to that loop hole I was looking for.

Thank you sir.
